name: Sync pipeline_scripts to Databricks Repo

on:
  push:
    paths:
      - "pipeline_scripts/**"   # Trigger only when changes occur in the pipeline_scripts folder
  workflow_dispatch:

jobs:
  sync-to-databricks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Configure Databricks CLI
      uses: databricks/setup-cli@main

    - name: Sync pipeline_scripts folder to Databricks Repo
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks repos update "/Repos/sangamdeuja/dbstreamingETL" --branch main

     
